language: node_js
node_js:
  - 4
  - 6
branches:
  except:
    - latest
    - production
    - /^v[0-9]\.[0-9]\.[0-9]$/
before_script:
  - npm install -g grunt-cli
  - ./create_config.sh
script:
  - npm test
  - './bin/order-export --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --targetDir foo --fileWithTimestamp true --exportType csv --csvTemplate data/template-order-simple.csv && ls foo | grep -qE "orders_[[:digit:]]+\.csv"'
  - './bin/order-export --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --targetDir foo --fileWithTimestamp true --exportType csv --csvTemplate data/template-order-addresses.csv && ls foo | grep -qE "orders_[[:digit:]]+\.csv"'
  - './bin/order-export --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --targetDir foo --fileWithTimestamp true --exportType csv --csvTemplate data/template-order-lineitems.csv && ls foo | grep -qE "orders_[[:digit:]]+\.csv"'
env:
  global:
    - secure: BT3EQ0Kzhbp1XZZER9Xq7AnVotA6cMbbNbzivqTxBoLtNogaQjYBW14MWnizMb8B7Z6HtUyw+fWU7PPKn0PIsyIBRzM5XEfVIf5HxRatyS75v51MOmzzPwz3TYN2DvzCxZWLe2Mrh2vZbr1twGK8TxE5V0ye80UiwkNsNJyhEa4= # host
    - secure: Tw459kNIYcSGyX5oU8XvJtd4jFGcq7YPV8TBeeuW4ju2LDMUPVrkuazrKzY51oDJwjumnt1d9lLpQFdYRMIm/k7R9hFqfHfnT0Rr3QzO3A1tKPmOFATfkSGNlQqnD+H7SEgAlBa/tnKS2F3/78wZdgiDhIubaLa9n9OsHth1zXc= # username
    - secure: DgU1phNgKAl9Tyk+2bNtle1ED6SBY6l9egD30B2X4WRhUCYYNoV9GPeKW8gnVX9GT/g50hho/0Iz5fD0aCjyCAyYTb1r0QGnLSG2eXHctX0AnulqFnvV3yAaDrcs0eR+knBPnEIJ3MyZPllB4G8eSturgE86NB04z3It0DtOECo= # psw
    - secure: b6tBp04ubVoUsOUb0SGTSwxvxRSc2bxbHcFsHX1VaBxRjunwd7MgxVgvWw2y/R7pc1PYEcFrXR+9soJi2JFy0krFNoHgnv7+liPlnna1wEPmTCkHw2t06gtNb51EAOUJMfV+MjUlKn74NubGmquuhE1bjwuS1Knz00KakxNkzgM= # target
notifications:
  hipchat:
    rooms:
      secure: KfiSn4mdhFHxUbWG2EFDFx01VBNNncS8RYRw6ROcxVOsiaevLx/yqh2Yi7fTxWcoyG6Mp31Cxvx6w+dB58wIiZxZijtrVCU/agu/WGP6y/f4C/i2mRsnCXgf6GIC6fUXZVlFQKS0MVNqsx0d7fmR8jEej2/j7+hAOKMh/NsMvgE=
    template:
    - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
sudo: false
