language: node_js
node_js:
  - 0.8
  - 0.9
  - '0.10'
before_script:
- echo '{}' > ${HOME}/elastic.json
- touch ${HOME}/.env
- ./create_config.sh
- grunt
env:
  global:
  - secure: SNe+NExYCusG5i07EjPEx0NAYrV8ezrgbpfcfOt/pZ5FtT8vXRNlNXwgUf9DN4yskbn+VMolvv4wnXwPxjLcOhlZIaZzWClGYwCtmAHP5UHPA0gFQ9HvethnpeEiZq9HAO0JD8aeSYpZ+vKCde1yfxi3kU5/lT5MgNLnGyBY0co=
  - secure: nAFfCB3Xxt+e5885lPqKcELSA5Aw/xkoGTi4TzX/WDuFw7cHGgSTFmn2xdE6k6tRBIrr4XcDp0jAjgoYfloXHiKeB2vIByVfljF43p6wA00tgyp+nZuuJOMCq/Z96ck6LCn5lJvrPxaeRsXfXd/F3Lk9L35wp1iopydMZeaAK0A=
  - secure: eRQFFMcuBU/uTq8U5f5yN+OO6lNQVVJzrqtLyccs2tK7pzZVvr2yXFmz1ZE3ttXkAxNFRKmiyyXm+f8bozB98aKSs0LVe0WvYkE1D3EDLmzTiKX7DTFcnqhXW3KWd/vs3CGq6SgEzZpYUQt61tJCMAdLhYrUzWNUqc0A3SgowgQ=
